version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y zip aws-cli # Install zip and AWS CLI
  build:
    commands:
      - echo Creating a ZIP file of all repository files...
      - zip -r repository.zip * # Add all files and directories into a ZIP file
  post_build:
    commands:
      - echo Uploading the ZIP file to S3...
      - aws s3 cp repository.zip s3://cal-app-bucket/repository.zip
artifacts:
  files:
    - '**/*'
  discard-paths: no
